name: local
variables:
  - name: baseUrl
    value: http://localhost:4000
  - name: accessToken
    value: ""
  - name: refreshToken
    value: ""
  - name: oldRefreshToken
    value: MtTviebxe5jZdJGC5T5WXMnroG30C_vwGeQ9W_KoWCxlK0nx6YhJnTdLFI-ONiDyXdZ5it9GCJ5oqPelFQHU_g
